# Generated by Django 4.2.2 on 2023-07-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compny2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('barty', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='sall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcode', models.FloatField()),
                ('namecode', models.CharField(max_length=100)),
                ('sall', models.IntegerField()),
            ],
        ),
    ]
