# Generated by Django 4.2.2 on 2023-07-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpt1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compny2',
            name='departhment',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
